"""
Account URL routes

=== LARAVEL COMPARISON ===
Like the routes generated by Auth::routes() in Laravel:
    GET  /login          — Show login form
    POST /login          — Handle login
    POST /logout         — Handle logout
    GET  /register       — Show registration form
    POST /register       — Handle registration

Django provides built-in views for login/logout!
You only need to write the register view yourself.
"""

from django.urls import path
from django.contrib.auth import views as auth_views  # Built-in auth views
from . import views

urlpatterns = [
    # ── Login ───────────────────────────────────────────────
    # Uses Django's BUILT-IN LoginView (no controller code needed!)
    # Like Laravel's Auth::routes() generating the login route
    # template_name tells it which HTML template to use
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'
    ), name='login'),

    # ── Logout ──────────────────────────────────────────────
    # Uses Django's BUILT-IN LogoutView
    # Like Laravel's: Route::post('/logout', [AuthController::class, 'logout']);
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # ── Register ────────────────────────────────────────────
    # This one we write ourselves (see accounts/views.py)
    path('register/', views.register, name='register'),

    # ── Profile ─────────────────────────────────────────────
    path('profile/', views.profile, name='profile'),
]
